import bcrypt from "bcryptjs";

import type {
  Complaint,
  Customer,
  Distributor,
  ManufacturedProduct,
  Product,
  RawMaterial,
  PendingRegistration,
  Sale,
  SerialEntry,
  User,
  UserRole,
} from "../types";

// NOTE: In production, replace these arrays with actual DB calls (Prisma/Postgres/etc).
export const db = {
  users: [
    {
      id: "u1",
      email: "admin@aurawatt.in",
      passwordHash: bcrypt.hashSync("Admin@123", 10),
      name: "Ansh",
      mobile: "9380482094",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u2",
      email: "accountsdept@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Accounts@123", 10),
      name: "Accounts Team",
      mobile: "9289968570",
      role: "Inventory Manager" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u3",
      email: "inventory@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Inventory@123", 10),
      name: "Inventory Team",
      mobile: "9380482094",
      role: "Inventory Manager" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u4",
      email: "sales@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Sales@123", 10),
      name: "Sales Team",
      mobile: "9380482094",
      role: "Sales Manager" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u5",
      email: "h2solar08@gmail.com",
      passwordHash: bcrypt.hashSync("H2Solar@123", 10),
      name: "H2 Solar",
      mobile: "9026233630",
      role: "Distributor" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as User[],

  pendingRegistrations: [] as PendingRegistration[],

  customers: [
    {
      id: "c1",
      name: "MAA VINDHYAVASINI ENTERPRISES",
      type: "Distributor" as const,
      email: "maavindhyavasini@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "c2",
      name: "GARHWAL SOLAR SOLUTION",
      type: "Individual" as const,
      email: "garhwalsolar@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Customer[],

  products: [
    {
      id: "p1",
      series: "AURAWATT LFP SERIES(12.4KW/240V/52AH)",
      model: "AW-LFP-240-52",
      createdAt: new Date(),
    },
    { id: "p2", series: "AURAWATT LFP SERIES(25.6V/100AH)", model: "AW-LFP-25.6", createdAt: new Date() },
    { id: "p3", series: "AURAWATT LFP SERIES(48V/60AH)", model: "AW-LFP-48-60", createdAt: new Date() },
    { id: "p4", series: "AURAWATT LFP SERIES(48V/70AH)", model: "AW-LFP-48-70", createdAt: new Date() },
    { id: "p5", series: "AURAWATT LFP SERIES(51.2V/100AH)", model: "AW-LFP-51.2", createdAt: new Date() },
    { id: "p6", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-3000", createdAt: new Date() },
    { id: "p7", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-4000", createdAt: new Date() },
    { id: "p8", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-5000", createdAt: new Date() },
    { id: "p9", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-6000", createdAt: new Date() },
    { id: "p10", series: "SP SERIES (5-11 KW / 48V / IP21)", model: "AW-SP-10000", createdAt: new Date() },
    { id: "p11", series: "TP-L SERIES", model: "AW-TP-8000-L", createdAt: new Date() },
    { id: "p12", series: "TP-L SERIES", model: "AW-TP-10000-L", createdAt: new Date() },
  ] as Product[],

  rawMaterials: [] as RawMaterial[],
  manufactured: [] as ManufacturedProduct[],
  serials: [] as SerialEntry[],
  sales: [] as Sale[],
  complaints: [] as Complaint[],

  distributors: [
    {
      id: "d1",
      name: "H2 SOLAR POWER PRIVATE LIMITED",
      email: "h2solar08@gmail.com",
      mobile: "9026233630",
      address: "Lucknow, Uttar Pradesh 226201",
      unitsSold: 85,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "d2",
      name: "DVH SOLAR GREEN ENERGY",
      email: "Harshrana1705@gmail.com",
      mobile: "7453040223",
      address: "Saharanpur, Uttar Pradesh",
      unitsSold: 14,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Distributor[],
};
