import bcrypt from "bcryptjs";

import type {
  Complaint,
  Customer,
  Distributor,
  ManufacturedProduct,
  Product,
  RawMaterial,
  PendingRegistration,
  Sale,
  SerialEntry,
  User,
  UserRole,
} from "../types";

// NOTE: In production, replace these arrays with actual DB calls (Prisma/Postgres/etc).
export const db = {
  users: [
    {
      id: "u1",
      email: "admin@aurawatt.in",
      passwordHash: bcrypt.hashSync("Admin@123", 10),
      name: "Ansh",
      mobile: "9380482094",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u2",
      email: "accountsdept@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Accounts@123", 10),
      name: "Accounts Team",
      mobile: "9289968570",
      role: "Accounts" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u3",
      email: "inventory@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Inventory@123", 10),
      name: "Inventory Team",
      mobile: "9380482094",
      role: "Inventory Manager" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u4",
      email: "sales@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Sales@123", 10),
      name: "Sales Manager",
      mobile: "9380482094",
      role: "Sales Manager" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-dispatch-demo",
      email: "dispatch@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Dispatch@123", 10),
      name: "Dispatch Team",
      mobile: "9380482094",
      role: "Dispatch" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-rohit",
      email: "l1.rohit@avavbusiness.com",
      passwordHash: bcrypt.hashSync("RohitL1@123", 10),
      name: "Rohit Sharma",
      mobile: "9380482101",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-amit",
      email: "l1.amit@avavbusiness.com",
      passwordHash: bcrypt.hashSync("AmitL1@123", 10),
      name: "Amit Verma",
      mobile: "9380482102",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-rahul",
      email: "l1.rahul@avavbusiness.com",
      passwordHash: bcrypt.hashSync("RahulL1@123", 10),
      name: "Rahul Sharma",
      mobile: "9380482103",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-aman",
      email: "l1.aman@avavbusiness.com",
      passwordHash: bcrypt.hashSync("AmanL1@123", 10),
      name: "Aman Singh",
      mobile: "9380482104",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-deepak-verma",
      email: "l1.deepak.verma@avavbusiness.com",
      passwordHash: bcrypt.hashSync("DeepakVermaL1@123", 10),
      name: "Deepak Verma",
      mobile: "9380482105",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l2-vikas",
      email: "l2.vikas@avavbusiness.com",
      passwordHash: bcrypt.hashSync("VikasL2@123", 10),
      name: "Vikas Yadav",
      mobile: "9380482201",
      role: "L2 Technical Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l2-sandeep",
      email: "l2.sandeep@avavbusiness.com",
      passwordHash: bcrypt.hashSync("SandeepL2@123", 10),
      name: "Sandeep Singh",
      mobile: "9380482202",
      role: "L2 Technical Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l3-mahesh",
      email: "l3.mahesh@avavbusiness.com",
      passwordHash: bcrypt.hashSync("MaheshL3@123", 10),
      name: "Mahesh Choudhary",
      mobile: "9380482301",
      role: "L3 Advanced OEM Support" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l3-deepak",
      email: "l3.deepak@avavbusiness.com",
      passwordHash: bcrypt.hashSync("DeepakL3@123", 10),
      name: "Deepak Meena",
      mobile: "9380482302",
      role: "L3 Advanced OEM Support" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-warehouse-demo",
      email: "warehouse@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Warehouse@123", 10),
      name: "Warehouse Team",
      mobile: "9380482094",
      role: "Warehouse Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-service-accounts-demo",
      email: "serviceaccounts@avavbusiness.com",
      passwordHash: bcrypt.hashSync("ServiceAccounts@123", 10),
      name: "Service Accounts Team",
      mobile: "9289968570",
      role: "Accounts Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-dealer-demo",
      email: "dealer@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Dealer@123", 10),
      name: "Dealer",
      mobile: "9026233630",
      role: "Dealer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u7",
      email: "h2solar08@gmail.com",
      passwordHash: bcrypt.hashSync("H2Solar@123", 10),
      name: "H2 Solar",
      mobile: "9026233630",
      role: "Distributor" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as User[],

  pendingRegistrations: [] as PendingRegistration[],

  customers: [
    {
      id: "c1",
      name: "MAA VINDHYAVASINI ENTERPRISES",
      type: "Distributor" as const,
      email: "maavindhyavasini@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "c2",
      name: "GARHWAL SOLAR SOLUTION",
      type: "Individual" as const,
      email: "garhwalsolar@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Customer[],

  products: [
    {
      id: "p1",
      series: "AURAWATT LFP SERIES(12.4KW/240V/52AH)",
      model: "AW-LFP-240-52",
      createdAt: new Date(),
    },
    { id: "p2", series: "AURAWATT LFP SERIES(25.6V/100AH)", model: "AW-LFP-25.6", createdAt: new Date() },
    { id: "p3", series: "AURAWATT LFP SERIES(48V/60AH)", model: "AW-LFP-48-60", createdAt: new Date() },
    { id: "p4", series: "AURAWATT LFP SERIES(48V/70AH)", model: "AW-LFP-48-70", createdAt: new Date() },
    { id: "p5", series: "AURAWATT LFP SERIES(51.2V/100AH)", model: "AW-LFP-51.2", createdAt: new Date() },
    { id: "p6", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-3000", hsnSac: "8504", gstRate: 5, dealerPrice: 120, distributorPrice: 100, createdAt: new Date() },
    { id: "p7", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-4000", hsnSac: "8504", gstRate: 5, dealerPrice: 120, distributorPrice: 100, createdAt: new Date() },
    { id: "p8", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-5000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p9", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-6000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p10", series: "SP SERIES (5-11 KW / 48V / IP21)", model: "AW-SP-10000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p11", series: "TP-L SERIES", model: "AW-TP-8000-L", createdAt: new Date() },
    { id: "p12", series: "TP-L SERIES", model: "AW-TP-10000-L", createdAt: new Date() },
    {
      id: "p-client-4kw",
      series: "Aurawatt SP Series-",
      model: "(AW-SP-4KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 120,
      distributorPrice: 100,
      createdAt: new Date(),
    },
    {
      id: "p-client-5kw",
      series: "Aurawatt SP Series-",
      model: "(AW-SP-5KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 240,
      distributorPrice: 200,
      createdAt: new Date(),
    },
    {
      id: "p-client-10kw",
      series: "Aurawatt SP Series-",
      model: "(AW-SP-10KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 240,
      distributorPrice: 200,
      createdAt: new Date(),
    },
    {
      id: "p-client-lfp-8504",
      series: "Li-ion (LFP) Battery - AW LVLFP -",
      model: "51.2V/100AH",
      hsnSac: "8504",
      gstRate: 18,
      dealerPrice: 360,
      distributorPrice: 300,
      createdAt: new Date(),
    },
    {
      id: "p-client-lfp-8507",
      series: "Li-ion (LFP) Battery - AW LVLFP -",
      model: "51.2V/100AH (HSN 8507)",
      hsnSac: "8507",
      gstRate: 18,
      dealerPrice: 480,
      distributorPrice: 400,
      createdAt: new Date(),
    },
  ] as Product[],

  rawMaterials: [] as RawMaterial[],
  manufactured: [] as ManufacturedProduct[],
  serials: [] as SerialEntry[],
  sales: [] as Sale[],
  complaints: [] as Complaint[],

  distributors: [
    {
      id: "d1",
      name: "H2 SOLAR POWER PRIVATE LIMITED",
      email: "h2solar08@gmail.com",
      mobile: "9026233630",
      address: "Lucknow, Uttar Pradesh 226201",
      unitsSold: 85,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "d2",
      name: "DVH SOLAR GREEN ENERGY",
      email: "Harshrana1705@gmail.com",
      mobile: "7453040223",
      address: "Saharanpur, Uttar Pradesh",
      unitsSold: 14,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Distributor[],
};
