import bcrypt from "bcryptjs";

import type {
  Complaint,
  Customer,
  Distributor,
  ManufacturedProduct,
  Product,
  RawMaterial,
  PendingRegistration,
  Sale,
  SerialEntry,
  User,
  UserRole,
} from "../types";

// NOTE: In production, replace these arrays with actual DB calls (Prisma/Postgres/etc).
export const db = {
  users: [
    {
      id: "u1",
      email: "admin@aurawatt.in",
      passwordHash: bcrypt.hashSync("Admin@123", 10),
      name: "Ansh",
      mobile: "9380482094",
      role: "Admin" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u2",
      email: "accountsdept@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Accounts@123", 10),
      name: "Accounts Team",
      mobile: "9289968570",
      role: "Accounts" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u3",
      email: "sales@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Sales@123", 10),
      name: "Sales Manager",
      mobile: "9380482094",
      role: "Sales Manager" as UserRole,
      isActive: true,
      assignedStates: ["UP"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-sales-head",
      email: "saleshead@avavbusiness.com",
      passwordHash: bcrypt.hashSync("SalesHead@123", 10),
      name: "Sales Head",
      mobile: "9380482110",
      role: "Sales" as UserRole,
      isActive: true,
      assignedStates: ["UP", "MP", "Rajasthan"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-sales-up",
      email: "sales.up@avavbusiness.com",
      passwordHash: bcrypt.hashSync("SalesUP@123", 10),
      name: "UP Sales",
      mobile: "9380482111",
      role: "Sales" as UserRole,
      isActive: true,
      assignedStates: ["UP"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-sales-mp",
      email: "sales.mp@avavbusiness.com",
      passwordHash: bcrypt.hashSync("SalesMP@123", 10),
      name: "MP Sales",
      mobile: "9380482112",
      role: "Sales" as UserRole,
      isActive: true,
      assignedStates: ["MP"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-sales-east",
      email: "sales.east@avavbusiness.com",
      passwordHash: bcrypt.hashSync("SalesEast@123", 10),
      name: "East Sales",
      mobile: "9380482113",
      role: "Sales" as UserRole,
      isActive: true,
      assignedStates: ["Bihar"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-sales-north",
      email: "sales.north@avavbusiness.com",
      passwordHash: bcrypt.hashSync("SalesNorth@123", 10),
      name: "North Sales",
      mobile: "9380482114",
      role: "Sales" as UserRole,
      isActive: true,
      assignedStates: ["Haryana", "Punjab"],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u4",
      email: "dispatch@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Dispatch@123", 10),
      name: "Dispatch Team",
      mobile: "9380482094",
      role: "Dispatch" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u5",
      email: "inventory@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Inventory@123", 10),
      name: "Inventory Team",
      mobile: "9380482095",
      role: "Inventory" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u6",
      email: "warehouse@avavbusiness.com",
      passwordHash: bcrypt.hashSync("Warehouse@123", 10),
      name: "Warehouse Team",
      mobile: "9380482096",
      role: "Warehouse Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-piyush",
      email: "l1.piyush@avavbusiness.com",
      passwordHash: bcrypt.hashSync("PiyushL1@123", 10),
      name: "Piyush",
      mobile: "9380482101",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-neeraj",
      email: "l1.neeraj@avavbusiness.com",
      passwordHash: bcrypt.hashSync("NeerajL1@123", 10),
      name: "Neeraj",
      mobile: "9380482102",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-nitin",
      email: "l1.nitin@avavbusiness.com",
      passwordHash: bcrypt.hashSync("NitinL1@123", 10),
      name: "Nitin",
      mobile: "9380482103",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-prashant-singh",
      email: "l1.prashant.singh@avavbusiness.com",
      passwordHash: bcrypt.hashSync("PrashantSinghL1@123", 10),
      name: "Prashant Singh",
      mobile: "9380482104",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-ashutosh",
      email: "l1.ashutosh@avavbusiness.com",
      passwordHash: bcrypt.hashSync("AshutoshL1@123", 10),
      name: "Ashutosh",
      mobile: "9380482105",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-rajat",
      email: "l1.rajat@avavbusiness.com",
      passwordHash: bcrypt.hashSync("RajatL1@123", 10),
      name: "Rajat",
      mobile: "9380482106",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-swastik",
      email: "l1.swastik@avavbusiness.com",
      passwordHash: bcrypt.hashSync("SwastikL1@123", 10),
      name: "Swastik",
      mobile: "9380482107",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l1-pradeep",
      email: "l1.pradeep@avavbusiness.com",
      passwordHash: bcrypt.hashSync("PradeepL1@123", 10),
      name: "Pradeep",
      mobile: "9380482108",
      role: "L1 Engineer" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l2-naveen-maurya",
      email: "l2.naveen.maurya@avavbusiness.com",
      passwordHash: bcrypt.hashSync("NaveenMauryaL2@123", 10),
      name: "Naveen Maurya",
      mobile: "9380482201",
      role: "L2 Technical Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l2-prashant-noida",
      email: "l2.prashant.noida@avavbusiness.com",
      passwordHash: bcrypt.hashSync("PrashantNoidaL2@123", 10),
      name: "Prashant Noida",
      mobile: "9380482202",
      role: "L2 Technical Team" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "u-l3-mahesh",
      email: "l3.mahesh@avavbusiness.com",
      passwordHash: bcrypt.hashSync("MaheshL3@123", 10),
      name: "Mahesh Choudhary",
      mobile: "9380482301",
      role: "L3 Advanced OEM Support" as UserRole,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as User[],

  pendingRegistrations: [] as PendingRegistration[],

  customers: [
    {
      id: "c1",
      name: "MAA VINDHYAVASINI ENTERPRISES",
      type: "Distributor" as const,
      email: "maavindhyavasini@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "c2",
      name: "GARHWAL SOLAR SOLUTION",
      type: "Individual" as const,
      email: "garhwalsolar@default.com",
      phone: "0000000000",
      status: "Active" as const,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Customer[],

  products: [
    {
      id: "p1",
      series: "AURAWATT LFP SERIES(12.4KW/240V/52AH)",
      model: "AW-LFP-240-52",
      createdAt: new Date(),
    },
    { id: "p2", series: "AURAWATT LFP SERIES(25.6V/100AH)", model: "AW-LFP-25.6", createdAt: new Date() },
    { id: "p3", series: "AURAWATT LFP SERIES(48V/60AH)", model: "AW-LFP-48-60", createdAt: new Date() },
    { id: "p4", series: "AURAWATT LFP SERIES(48V/70AH)", model: "AW-LFP-48-70", createdAt: new Date() },
    { id: "p5", series: "AURAWATT LFP SERIES(51.2V/100AH)", model: "AW-LFP-51.2", createdAt: new Date() },
    { id: "p6", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-3000", hsnSac: "8504", gstRate: 5, dealerPrice: 120, distributorPrice: 100, createdAt: new Date() },
    { id: "p7", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-4000", hsnSac: "8504", gstRate: 5, dealerPrice: 120, distributorPrice: 100, createdAt: new Date() },
    { id: "p8", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-5000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p9", series: "SP SERIES (3-6 KW / 48V / IP66)", model: "AW-SP-6000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p10", series: "SP SERIES (5-11 KW / 48V / IP21)", model: "AW-SP-10000", hsnSac: "8504", gstRate: 5, dealerPrice: 240, distributorPrice: 200, createdAt: new Date() },
    { id: "p11", series: "TP-L SERIES", model: "AW-TP-8000-L", createdAt: new Date() },
    { id: "p12", series: "TP-L SERIES", model: "AW-TP-10000-L", createdAt: new Date() },
    {
      id: "p-client-4kw",
      series: "Aurawatt SP Series-",
      model: "(AW-SP-4KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 120,
      distributorPrice: 100,
      createdAt: new Date(),
    },
    {
      id: "p-client-5kw",
      series: "Aurawatt SP Series-",
      model: "(AW-SP-5KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 240,
      distributorPrice: 200,
      createdAt: new Date(),
    },
    {
      id: "p-client-10kw",
      series: "Aurawatt SP Series-",
      model: "(AW-SP-10KW/48V Inverter)",
      hsnSac: "8504",
      gstRate: 5,
      dealerPrice: 240,
      distributorPrice: 200,
      createdAt: new Date(),
    },
    {
      id: "p-client-lfp-8504",
      series: "Li-ion (LFP) Battery - AW LVLFP -",
      model: "51.2V/100AH",
      hsnSac: "8504",
      gstRate: 18,
      dealerPrice: 360,
      distributorPrice: 300,
      createdAt: new Date(),
    },
    {
      id: "p-client-lfp-8507",
      series: "Li-ion (LFP) Battery - AW LVLFP -",
      model: "51.2V/100AH (HSN 8507)",
      hsnSac: "8507",
      gstRate: 18,
      dealerPrice: 480,
      distributorPrice: 400,
      createdAt: new Date(),
    },
  ] as Product[],

  rawMaterials: [] as RawMaterial[],
  manufactured: [] as ManufacturedProduct[],
  serials: [] as SerialEntry[],
  sales: [] as Sale[],
  complaints: [] as Complaint[],

  distributors: [
    {
      id: "d1",
      name: "H2 SOLAR POWER PRIVATE LIMITED",
      email: "h2solar08@gmail.com",
      mobile: "9026233630",
      address: "Lucknow, Uttar Pradesh 226201",
      unitsSold: 85,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "d2",
      name: "DVH SOLAR GREEN ENERGY",
      email: "Harshrana1705@gmail.com",
      mobile: "7453040223",
      address: "Saharanpur, Uttar Pradesh",
      unitsSold: 14,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ] as Distributor[],
};
